### ISSUE TITLE
Future composer require taocomp/php-sdicoop-server

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-sdicoop-server#1]
Ciao ancora Ale*!

Senti ma se aggiungessi anche questa distro su https://packagist.org/ ?
Così potremmo scaricare e gestire aggiornamenti tramite composer require taocomp/php-sdicoop-server =)

*ricorda che lasciamo il tuo nome su i Credits del portale 🥇

**Comment by aded** [comment]
Apropos, se vi va mandatemi il link del progetto a cui state lavorando. :-)

**Comment by MwSpaceLLC** [comment]
Volentieri caro, ma prima devo ancora terminarlo 😖...
Sono solamente io a svilupparlo,
e dopo aver messo su debian 9 su google cloud sto sviluppando il crm con laravel
sono ancora alla costruzione delle fatture, 
quando ho terminato anche il front , ti contatto in privato e se mi lasci i tuoi contatti ti mando il link ovviamente su allow IP.
ma la buona è che questo progetto sarà Obbligatoriamente Free 😜 (anche le API)
Ti saluto e ti auguro un Buon Natale se non i si risente Ale, 

Aleksandr Ivanovitch, CTO/CEO & Founder di MwSpace LLC
