### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-sdicoop-server#2]
Ciao Ale.
So che **non è un errore**, ma ti riporto il composer dopo l'aggiunta del apcchetto 🔢 

```
Warning: Ambiguous class resolution, "Taocomp\Einvoicing\Sdicoop\TestSdiRiceviFile" was found in both 

"/vendor/taocomp/php-sdicoop-client/src\SdiRiceviFile.php" 
and 

"/vendor/taocomp/php-sdicoop-client/src\TestSdiRiceviFile.php", the first w
ill be used.

Warning: Ambiguous class resolution, "Taocomp\Einvoicing\Sdicoop\TestSdiRiceviNotifica" was found in both 
"vendor/taocomp/php-sdicoop-client/src\SdiRiceviNotifica.php" 
and 
"vendor/taocomp/php-sdicoop-client/src\TestSdiRiceviNotifica.php",

 the first will be used.

Warning: Ambiguous class resolution, "Taocomp\Einvoicing\Sdicoop\FileSdI" was found in both 
"vendor/taocomp/php-sdicoop-client/src/FileSdI.php"
and
 "/vendor/taocomp/php-sdicoop-server/src\FileSdI.php", the first will be used.

Warning: Ambiguous class resolution,
 "Taocomp\Einvoicing\Sdicoop\FileSdIBase" was found in both 
"/vendor/taocomp/php-sdicoop-client/src/FileSdIBase.php" 
and
 "/vendor/taocomp/php-sdicoop-server/src\FileSdIBase.php", the first will be used.
```

Le 2 classi test e di produzione penso che siano uguali ?😋:

###TestSdiRiceviFile.php
`
class TestSdiRiceviFile extends Client
{
    const ENDPOINT = 'https://testservizi.fatturapa.it/ricevi_file';
    const WSDL     = __DIR__ . '/../assets/wsdl/SdIRiceviFile_v1.0.wsdl';
}
`

###SdiRiceviFile.php
`
class TestSdiRiceviFile extends Client
{
    const ENDPOINT = 'https://servizi.fatturapa.it/ricevi_file';
    const WSDL     = __DIR__ . '/../assets/wsdl/SdIRiceviFile_v1.0.wsdl';
}
`
Le rinomini tu o Io ? 🤗
se lo fai tu, poi con composer update mi si aggiornano i pacchetti automaticamente 😍

Salutissimi!

**Comment by aded** [comment]
Ciao, per le prime due aggiorna il pacchetto "-client": quelle classi non ci sono più. Usa direttamente la classe Client come indicato nel README.

Per le altre due temevo potesse accadere, ma in realtà è un warning che puoi ignorare perché sono pressoché uguali (o lo saranno a breve). Però devo risolverlo in qualche modo: si verifica quando client e server vengono utilizzati all'interno dello stesso codice come nel tuo caso :-), finora li ho sempre usati su macchine diverse.

Fammi intanto sapere se è tutto ok con le prime due del client.

**Comment by aded** [comment]
Una possibilità è cambiare i namespace in questo modo:
Server: Taocomp\Einvoicing\Sdicoop\Server
Client: Taocomp\Einvoicing\Sdicoop\Client

Ti faccio sapere quanto prima.

**Comment by MwSpaceLLC** [comment]
ok, aggiornameto fatto !

```
 composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating taocomp/php-sdicoop-client (v0.1.3 => v0.1.4): Downloading (100%)
Writing lock file
Generating optimized autoload files
```
Per le altre 2 senza problemi. attendo. Tanto ancora dobbiamo finire anche l'invio tramite sdiSftp 🤗

xk il ns server lavora sia con lo sdicoop che con lo sdiftp 😋

**Comment by aded** [comment]
Namespaces changed as follow:
Server: `Taocomp\Einvoicing\SdicoopServer`
Client: `Taocomp\Einvoicing\SdicoopClient`
