### ISSUE TITLE
Problemi di installazione

### ISSUE THREAD

**Issue by robyone67** [taocomp/php-sdicoop-server#3]
Salve, ho provato ad installare il progetto, scaricando e copiando il repository su un server linux-apache con php 7, ma quando provo a richiamare il metodo RiceviFatture con un client, si verifica un "PHP Fatal error:  Class 'SoapServer' not found in …./src/WebService.php on line 24". Potete aiutarmi? Grazie.

**Comment by aded** [comment]
Ciao, il pacchetto php-soap è installato?

**Comment by robyone67** [comment]
No, hai ragione, me ne sono accorto dopo…. Su php 7 il soap non è installato di default e quindi ho provveduto ad installarlo. Adesso proverò il tuo progetto, se ho problemi ti faccio sapere… ;-)
Grazie per la risposta.
